name: scrape & push

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' 

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write # push changes to repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -e .

      - name: Run ADP scraper
        run: |
          python -m adp_scraper.main

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add adp_database/*.json adp.json
          git diff --quiet || git commit -m "Update scraped ADP data"
          git push